### ISSUE TITLE
Adding extra maintainers to geotiff crate

### ISSUE THREAD

**Issue by weiji14** [georust/meta#34]
Hi there,

A bunch of us are interested in maintaining and contributing to the georust/geotiff repo (see discussion at https://github.com/georust/geotiff/issues/7). Would it be possible to grant me (@weiji14) and @gschulze maintain rights?

Thanks!

**Comment by urschrei** [comment]
Fine with me (on behalf of the shadowy Georust decision-making entity). @dominikbucher are you OK with these additions?

**Comment by frewsxcv** [comment]
Sounds good to me too ✅

**Comment by dominikbucher** [comment]
Sure thing, I added maintain rights for both @weiji14 and @gschulze. Thanks for pushing geotiff forward!! Let me know if I can be of any help in any way (time's always scarce but that's the same for everyone I guess 🤷🏻‍♂️)!

**Comment by gschulze** [comment]
@dominikbucher, @frewsxcv, @urschrei thank you for your trust! I'm excited to contribute and move things forward!

**Comment by weiji14** [comment]
Yay, thanks @dominikbucher! I'll close this issue now, but will reopen if we need to add other people to georust/geotiff.

(I did wonder if there should be a georust/geotiff [team](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams), but maybe better to ask that on separately at https://github.com/georust/meta/issues/11).

**Comment by feefladder** [comment]
Hey, I've been also wondering for myself if I want to be a maintainer of georust/geotiff. As it's a free-time/nonmonetized thing, I would want my relationship to be reciprocal. It's a bit of a try-out for me here, but here's a small overview:
- As an Indigenous Frisii (Lowlander/Dutchie who recognized/reconciled and participates from their indignousness), I want the things I do to be in service of my environment. This software (GeoData) can be used in very good (climate mitigation) and very bad (war, petrochemistry) ways. [There](https://www.boringcactus.com/2020/08/13/post-open-source.html) [is](https://writing.kemitchell.com/2019/03/15/Ethical-Subcommons.html) [more](https://www.gida-global.org/care) [background](https://gitlab.opengeohub.org/fee.gevaert/principle-layouts/-/blob/main/principles/care_practice.png) to it, and I'm open to discuss anything. Since this is about me, I think it is not off-topic, and I'm also (a bit sad, actually) if that means I won't be a maintainer.
- I don't know what and if a license change (Add a one-line license which only includes a "This software shall be used for Good, not Evil) (Crates.IO allows for logical ops on licenses) or more to create a spearheaded community towards [Creating Sustainable, Harmonious, Prosperous](https://www.fwii.net/profiles/blogs/sixteen-guiding-principles-for) world around the georust ecosystem.

I _do_ know that I can make a long-term dedication to georust, not sure if this crate or more GeoBevy-type apps.

**Comment by urschrei** [comment]
Hi @feefladder I'm not sure whether you're asking something here. If you'd like to be considered as a maintainer, please open an issue after you've resolved the questions you appear to be asking yourself. License changes are another, separate issue.
